# Generated by Django 3.0.3 on 2020-04-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_publishing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishing',
            name='plantbuddy',
        ),
        migrations.DeleteModel(
            name='PlantBuddy',
        ),
        migrations.DeleteModel(
            name='Publishing',
        ),
    ]
